### ISSUE TITLE
Return alphas as option to CPCA() class

### ISSUE THREAD

**Issue by gtiao** [abidlabs/contrastive#9]
I'm running cPCA on my dataset in a lot of different configurations and plotting the cPCs in my own script. It would be great if I could get the alphas returned so that I can add them to my plot titles. It looks like you do have a `return_alphas` option in your code, but it's not a top-level exposed parameter, and it would be great to have this as an option.

Thanks for putting together this great package!

**Comment by abidlabs** [comment]
Hi @gtiao, thanks for the feedback. You should be able to get the alphas returned by simply passing `return_alphas=True` as a parameter into your `fit` or `transform`. Does that not work for you? For example: 

`mdl.fit_transform(foreground_data, background_data, return_alphas=True)`

**Comment by gtiao** [comment]
Oh, good point. I thought I needed to pass the `return_alphas` flag into the model, e.g., `mdl = CPCA(return_alphas=True)`, but it works as you said. Thanks!
